### ISSUE TITLE
Improve Error Handling

### ISSUE THREAD

**Issue by lshlyapnikov** [lshlyapnikov/prm.js#26]
catch and report exceptions.
Running:
```
$ yarn build-cli && yarn start-cli --api-key=<API_KEY> --start-date=2017-11-21 --end-date=2020-11-23 \
 --annual-risk-free-interest-rate=1.0 --stocks=F,GOOG,XOM,BAC,INTC,PG,WMT \
 --delay-millis=0 --cache-date=2020-11-24 --number-of-simulations=-1000 --output-file=./output.json
```
reports:
```
[2020-11-27T00:50:53.385] [ERROR] cli/prm.js - Error: {"success":false,"error":{}}
```
Need to see the exact exception.

**Comment by lshlyapnikov** [comment]
This has already been fixed. Getting:
```
[2020-12-13T15:38:53.490] [ERROR] cli/prm.js - Error: Invalid numberOfSimulations: -1000. Min allowed: 100
    at failure (/home/lshlyapnikov/Projects/prm.js/build-cli/server/utils.js:46:14)
    at PrmController.simulate (/home/lshlyapnikov/Projects/prm.js/build-cli/server/prmController.js:100:33)
    at /home/lshlyapnikov/Projects/prm.js/build-cli/cli/prm.js:263:107
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 1)
```
